package sidx

// TODO use embed package when AppEngine/Go 1.16 released

const packageHeaderTemplate = `
{{ define "packageHeader" }}
// generated by sidx; DO NOT EDIT
package {{ .PackageIdent }}
{{ end }}
`

const fileTemplate = `
{{ template "packageHeader" .}}
{{- $b := . -}}
{{- range $_, $idx := .Indices -}}
// {{ $b.VarNamePrefix }}{{ $idx.Name.Name }} contains index for {{ $idx.TableName.Name }} table.
// "{{ $idx.SQL }}".
const {{ $b.VarNamePrefix }}{{ $idx.Name.Name }} = "{{ $idx.Name.Name }}"
{{ end -}}
`
