package sidx

// TODO use embed package when AppEngine/Go 1.16 released

const packageHeaderTemplate = `
{{ define "packageHeader" }}
// generated by sidx; DO NOT EDIT
package {{ .PackageIdent }}

import "github.com/vvakame/spatk/sidx"

var _ *sidx.Index = nil
{{ end }}
`

const fileTemplate = `
{{ template "packageHeader" .}}
{{- $b := . -}}
{{- range $_, $idx := .Indices -}}
// {{ $b.VarNamePrefix }}{{ $idx.Name }} contains index for {{ $idx.Table }} table.
// "{{ $idx.SQL }}".
const {{ $b.VarNamePrefix }}{{ $idx.Name }} = &sidx.Index{
	Name: {{ quote $idx.Name }},
	Table: {{ quote $idx.Table }},
	SQL: {{ quote $idx.SQL }},
	Unique: {{ $idx.Unique }},
	NullFiltered: {{ $idx.NullFiltered }},
}
{{ end -}}
`
